AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ImageId:
    Description: The AMI id eg ami-0ea87431b78a82070 Amazon Linux
    Type: String
  AvailabilityZone:
    Description: AZ for the instance
    Type: String
  InstanceType:
    Description: Eg. t2.micro
    Type: String
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
